version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./apps/backend/.env
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
