export const ACTION_NAMES = {
  LAUNCH_PUMPFUN_TOKEN: "LAUNCH_PUMPFUN_TOKEN_ACTION",
  GET_TOKEN_DATA_BY_TICKER: "GET_TOKEN_DATA_BY_TICKER_ACTION",
  GET_TOKEN_DATA_BY_ADDRESS: "GET_TOKEN_DATA_BY_ADDRESS_ACTION",
  JUPITER_SWAP: "JUPITER_SWAP_ACTION",
  GET_TOKEN_TOP_HOLDERS: "GET_TOKEN_TOP_HOLDERS_ACTION",
  GET_TOKEN_CHART_ADDRESS: "GET_TOKEN_CHART_ADDRESS_ACTION",
} as const;
